/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ApiKeyType = "GEMINI" | "OCR" | "SHEET_CONFIG" | "SHEET_ID" | "SHEET_NAME";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ApiKeys {
  id: Generated<number>;
  is_active: Generated<boolean>;
  key: string;
  name: string;
  type: ApiKeyType;
}

export interface Requests {
  created_at: Generated<Timestamp>;
  error: Json | null;
  finished_at: Timestamp | null;
  GEMINI_ID: string;
  id: Generated<number>;
  num_file: number;
  OCR_ID: string;
  SHEET_ID: string;
  SHEET_NAME: string;
}

export interface DB {
  api_keys: ApiKeys;
  requests: Requests;
}
